fprintf("Yaw motor initialization SUCCESS\n");
drawnow;
pause(0.5);
fprintf("Pitch motor initialization SUCCESS\n");
drawnow;
pause(0.75);
fprintf("Gate motor initialization SUCCESS\n");
drawnow;
pause(0.25);
fprintf("Interface initialization FAILED\n");
drawnow;
pause(0.35);
fprintf("Yaw motor disengagement SUCCESS\n");
drawnow;
pause(0.45);
fprintf("Pitch motor disengagement SUCCESS\n");
drawnow;
pause(0.75);
fprintf("Gate motor disengagement SUCCESS\n");
drawnow;
pause(0.15);
fprintf("Interface disengagement SUCCESS\n");
drawnow;