fprintf("Yaw motor initialization SUCCESS\n");
drawnow;
pause(0.5);
fprintf("Pitch motor initialization SUCCESS\n");
drawnow;
pause(0.75);
fprintf("Gate motor initialization SUCCESS\n");
drawnow;
pause(0.25);
fprintf("Interface initialization SUCCESS\n");
drawnow;
%pause(0.35);
%fprintf("[INIT FAIL] One or more of your devices failed to initialize. You may\n1) Retry\n2) Troubleshoot\n3) Continue Anyway (unsafe)\n");
fprintf("[INIT SUCCESS] All components initialized. Proceeding to zero all motors\n");
pause(1.75);
fprintf("Yaw motor zeroed at 5123\n");
drawnow;
pause(1.75);
fprintf("Pitch motor zeroed at 5123\n");
drawnow;
pause(1.75);
fprintf("Gate motor zeroed at 5123\n");
fprintf("[LOCALIZATION SUCCESS] All motors are localized");
drawnow;
pause(3.25);
fprintf("Yaw motor disengagement SUCCESS\n");
drawnow;
fprintf("Yaw motor disengagement SUCCESS\n");
drawnow;
pause(0.45);
fprintf("Pitch motor disengagement SUCCESS\n");
drawnow;
pause(0.75);
fprintf("Gate motor disengagement SUCCESS\n");
drawnow;
pause(0.15);
fprintf("Interface disengagement SUCCESS\n");
drawnow;